// pex_kantine/frontend/src/pages/App.tsx
import { BrowserRouter, Route, Routes } from "react-router-dom";
import Layout from "../assets/Layout";
import Home from "./Home";
import AdminLogin from "./AdminLogin";

function App() {
    return (
        <>
            <BrowserRouter>
                <Routes>
                    <Route path="/" element={<Layout />}>
                        <Route index element={<Home />} />
                        <Route path="admin-login" element={<AdminLogin />} />
                    </Route>
                </Routes>
            </BrowserRouter>
        </>
    );
}

export default App;

// firebase-test/src/App.svelte
<script>
    import { Router, Link, Route } from "svelte-routing";
    import Home from "./routes/Home.svelte";
    import Login from "./routes/Login.svelte";
    import Register from "./routes/Register.svelte";
</script>

<Router>
    <nav>
        <Link to="/">Home</Link>
        <Link to="/login">Login</Link>
        <Link to="/register">Register</Link>
    </nav>
    <div>
        <Route path="/"><Home /></Route>
        <Route path="/login" component={Login} />
        <Route path="/register" component={Register} />
    </div>
</Router>
